### ISSUE TITLE
readme could use an update

### ISSUE THREAD

**Issue by hol430** [PlantandFoodResearch/APSIM_Docker#1]
APSIM has moved to git (hosted on github) but the instructions in the readme still point to the old subversion repo. As far as I know, the subversion repo is still accessible(?) but this may not always be the case.

**Comment by eburgueno** [comment]
Hi @hol430, thanks for the update. I wasn't aware that APSIMClassic had been migrated to Git on GitHub.

I would actually prefer to deprecate this repo since we don't user Docker anymore. I will try and do something similar to what we did for [ApsimX on Singularity](https://github.com/powerPlant/apsimx-srf).

The recipes we used for Apsim Classic have not been published yet because they include `CottonPassword.txt`, which (back then) was not publicly available. I see that you can now get it from apsimdev.apsim.info as published [here](https://github.com/APSIMInitiative/Docker/blob/c2e3600d18338a6e089807f3507c92f724440492/OldApsim/Compile/dockerfile#L45), so presumably this is no longer a problem.

**Comment by hol430** [comment]
Makes sense. Unsure if this is useful or not for you but you can call [our webservice](http://apsimdev.apsim.info/APSIM.Builds.Service/Builds.svc/GetURLOfLatestVersion?operatingSystem=Debian) to fetch the installer for the latest version (of apsimx) if need be.

**Comment by eburgueno** [comment]
Archiving repo so closing this issue.
